version: '3.8'

services:
  # Servicio de la aplicación Bagisto (PHP-FPM + Nginx)
  bagisto_app:
    build:
      context: . # El contexto de construcción es la carpeta actual (bagisto-docker)
      dockerfile: Dockerfile # Usa el Dockerfile que crearemos
    image: bagisto-app:latest # Nombre de la imagen Docker
    container_name: bagisto_app # Nombre del contenedor
    ports:
      - "80:80" # Mapea el puerto 80 del host al puerto 80 del contenedor (para Nginx)
    volumes:
      # Monta la carpeta 'app' de tu host al directorio de trabajo en el contenedor.
      # ¡Aquí es donde estará el código de Bagisto!
      - ./app:/var/www/html
    depends_on:
      - bagisto_db # Asegura que la base de datos se inicie antes que la aplicación
    environment:
      # Variables de entorno para Bagisto (Laravel) - ¡Se leen desde el .env del contenedor!
      # Estas serán utilizadas por Bagisto para conectarse a la DB.
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost # Cambia esto si usas un dominio diferente
      DB_CONNECTION: mysql
      DB_HOST: bagisto_db # El nombre del servicio de la DB en docker-compose.yml
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-bagisto} # Usa la variable del .env o 'bagisto' por defecto
      DB_USERNAME: ${DB_USERNAME:-bagisto_user}
      DB_PASSWORD: ${DB_PASSWORD:-bagisto_password}
    networks:
      - bagisto_network

  # Servicio de la base de datos MySQL
  bagisto_db:
    image: mysql:8.0 # Bagisto 2.x requiere MySQL 8.0+
    container_name: bagisto_db
    ports:
      - "3306:3306" # Mapea el puerto 3306 del host al puerto 3306 del contenedor
    volumes:
      - db_data:/var/lib/mysql # Volumen para persistencia de datos de la DB
    environment:
      # Variables de entorno para la configuración de MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password} # Contraseña del usuario root de MySQL
      MYSQL_DATABASE: ${DB_DATABASE:-bagisto} # Nombre de la base de datos
      MYSQL_USER: ${DB_USERNAME:-bagisto_user} # Usuario de la base de datos
      MYSQL_PASSWORD: ${DB_PASSWORD:-bagisto_password} # Contraseña del usuario de la base de datos
    networks:
      - bagisto_network

  # Servicio de PhpMyAdmin para gestionar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - bagisto_db:mysql # Enlaza con el servicio de la DB (para compatibilidad)
    ports:
      - "8081:80" # Accede a PhpMyAdmin en http://localhost:8081
    environment:
      PMA_HOST: bagisto_db # Host de la base de datos al que se conectará PhpMyAdmin
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password} # Para loguearse con root
    networks:
      - bagisto_network

# Definición de volúmenes para persistencia de datos
volumes:
  db_data: # Volumen para los datos de MySQL

# Definición de la red para que los contenedores puedan comunicarse entre sí
networks:
  bagisto_network:
    driver: bridge